[package]
name = "engine"
version = "0.1.0"
edition = "2021"

[dependencies]
winit             = "0.30"
ash               = "0.38"
ash-window        = "0.13"
raw-window-handle = "0.6"
glam              = "0.32"
memoffset         = "0.5.1"
image             = { version = "0.23", default-features = false, features = ["png"] }
num               = "0.2"
dirs              = "5"
kira              = { version = "0.12", default-features = false, features = ["cpal", "mp3"] }

[dependencies.bitflags]
version = ">= 1.0.4"
